 table "users1" (
    "user_id" SERIAL PRIMARY KEY,
    "username" VARCHAR
);

drop table users;

-- no se puede insertar user_id de manera manual
create table "users" (
    "user_id" INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    "username" VARCHAR
);

create table "users3" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
    "username" VARCHAR
);

create table "users4" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY (start with 100 increment by 2),
    "username" VARCHAR
);


insert into users (username) values ('Alberto');

select * from users;


-- combinacion de clave primaria

create table users_dual (
	id1 int,
	id2 int,
	primary key (id1, id2)
);

-- UUID

create extension if not exists "uuid-ossp";

select gen_random_uuid();

create table users_uuid(
	id uuid Default uuid_generate_v4() PRIMARY KEY);
		
alter table users_uuid add column name Text not null;

-- Secuence
create sequence user_sequence;
drop sequence user_sequence;

select currval('user_sequence'), nextval('user_sequence');

create table users6(
"user_id" INTEGER PRIMARY KEY default(nextval('user_sequence')),
"username" VARCHAR
);
